language: haxe
dist: xenial
os:
  - mac
  - linux
  - windows
haxe:
  - stable
  - development

matrix:
# Allow Haxe development to fail.
allow_failures:
  - haxe: development

script: ./test-travis.sh